### ISSUE TITLE
Check color ratio in CQL expression fields

### ISSUE THREAD

**Issue by juliet-rubini** [cqframework/sample-content-ig#53]
For 508 compliance, the color ratio needs to be 4.5:1.  Please confirm if this is the current ratio.  Thanks!

**Comment by echicoine-icf** [comment]
It DOES fail. Using WAVE (a tool for analyzing 508 compliance of web apps) it dings it over and over. The text color to background color fails to meet the minimum needed.
 
Solution is not on our end. Can't make the change with the liquid template because it's referencing a css class that HL7 defines at the central template repository.
